site:
#  <editor-fold desc="开发配置区，此为开发配置，打包时会自动删除，打包完成后会自动修复">
  data-path: D:/detectData/
#  </editor-fold>
#  <editor-fold desc="打包配置区，此为打包配置，开发时会自动注释">
#  data-path: /run/detectData/
#  </editor-fold>

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/detect?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
#    <editor-fold desc="开发配置区，此为开发配置，打包时会自动删除，打包完成后会自动修复">
    password: '!testcentremysqlDL1119!'
#    </editor-fold>
#    <editor-fold desc="打包配置区，此为打包配置，开发时会自动注释">
#    password: 'Abc==123'
#    </editor-fold>
    driver-class-columnName: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:static/,file:${site.data-path}

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

sqlmeta:
  connect-info:
    url: jdbc:sqlserver://localhost:1433;databaseName=sllaid;
    username: sa
    password: '123456'
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sync-step: "0 0/1 * * * ?"   #配置定时同步间隔

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  queryType-aliases-package: com.bjj.detect.entity
  type-handlers-package: com.syzx.framework.dao.handler
  configuration:
    default-enum-type-handler: com.syzx.framework.dao.handler.EnumTypeHandler
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#<editor-fold desc="开发配置区，此为开发配置，打包时会自动删除，打包完成后会自动修复">
server:
  port: 8081
  servlet:
    context-path: /detect
#</editor-fold>

syzxframework:
  generator:
    entity-package: com.bjj.detect.entity
#    <editor-fold desc="开发配置区，此为开发配置，打包时会自动删除，打包完成后会自动修复">
    update-strategy: create
#    </editor-fold>
#    <editor-fold desc="打包配置区，此为打包配置，开发时会自动注释">
#    update-strategy: create
#    </editor-fold>
  log:
    targets: 2
    rules: 15
  communication:
    session-expiry: 120000
  web:
    token-expiry: 600000
  protocol:
    message-package: com.bjj.detect.protocol.messages
    handler-package: com.bjj.detect.protocol.handlers
#    codec-package: com.bjj.detect.protocol.codecs
#    server-package: com.bjj.detect.protocol.servers

  launcher:
#    servers:
#      - {templateClass: com.syzx.framework.protocol.servers.jt808.Jt808UdpServer, name: Jt808Udp通信服务器, port: 8997}
#      - {templateClass: com.syzx.framework.protocol.servers.jt808.Jt808TcpServer, name: Jt808Tcp通信服务器, port: 8998}
